openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Contact Book
tags:
  - name: Contacts
    description: Operation with contacts
servers:
  - url: http://localhost:8080
paths:
  /contacts:
    post:
      $ref: ../swagger/paths/contacts/post.yaml
    get:
      $ref: ../swagger/paths/contacts/get.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/del.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
